print("Anuj Agrawal")
print("EB01")
print("E19CSE327")
print("DEVOPS LAB EXAM")
print("CSET483 Career Skills")
print("CSET308 Communicaton skills")
print("ECSE320L High Performance Computing")
print("ECSE306 Undergrad Research")
print("ECSE321 Seminar")
print("ECSE398 Capstone")
print("ECSE446 ADBMS")
print("ECSE460 Devops")
print("ESEA301 Environment")
